name: Build and Run Automated Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.26'

      - name: Configure CMake
        # sqlite3 handled by CMake
        run: cmake -S . -B build -G "Ninja"

      - name: Build
        run: cmake --build build

      - name: Test
        run: ./bin/testing