name: Build and Run Automated Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install CMake
        run: |
          $url = 'https://github.com/Kitware/CMake/releases/download/v3.26.0/cmake-3.26.0-windows-x86_64.msi'
          $output = 'cmake.msi'
          Invoke-WebRequest -Uri $url -OutFile $output
          Start-Process msiexec.exe -Wait -ArgumentList '/i', $output, '/quiet', '/norestart'
          echo "C:\Program Files\CMake\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set up Visual Studio Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: ./bin/testing
